---
os: linux
dist: bionic
language: node_js
node_js:
- lts/*
notifications:
  slack: dekalabs:"${TRAVIS_TOKEN}"
  template:
    - "*Project:* %{repository_name}"
    - "*Build:* <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}"
    - "*Duration:* %{duration}"
    - "*Result:* %{result}"
    - "*Message:* %{message}"
env:
  global:
  - PROJECT_NAME=climatenft
  - REPO_NAME=climate-nft-causes-api
jobs:
  include:
  - stage: test
    if: "(branch = develop AND (type = pull_request OR type = push))"
    before_script:
    - cp .env.example .env
    script:
    - yarn test
  - stage: build and push latest
    if: "(branch = develop AND type = push)"
    services:
    - docker
    script:
    - VERSION=`node -p "require('./package.json').version"`
    - IMAGE_ID=registry.dekaside.com/$PROJECT_NAME/$REPO_NAME
    - docker build . -f ./compose/production/Dockerfile --tag $IMAGE_ID:latest --tag
      $IMAGE_ID:$VERSION
    - echo "$HARBOR_PASSWORD" | docker login registry.dekaside.com --username "$HARBOR_USERNAME"
      --password-stdin
    - docker push $IMAGE_ID:$VERSION
    - docker push $IMAGE_ID:latest

